services:
  ai-resume-screener:
    build: .
    image: ai-resume-screener
    container_name: AI-Resume-Screener
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/.venv
      - /app/.git
      - /app/__pycache__
    environment:
      - STREAMLIT_SERVER_PORT=8501
    restart: always
